use crate::models::export::*;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ExportError {
    #[error("Mayaが見つかりません。maya_pathを設定してください")]
    MayaNotFound,
    #[error("入力ファイルが見つかりません: {0}")]
    InputNotFound(String),
    #[error("エクスポート失敗: {0}")]
    ExportFailed(String),
    #[error("I/Oエラー: {0}")]
    IoError(#[from] std::io::Error),
    #[error("JSONエラー: {0}")]
    JsonError(#[from] serde_json::Error),
}

pub type Result<T> = std::result::Result<T, ExportError>;

/// MB→FBXエクスポートサービス
pub struct ExportService {
    config: MbExportConfig,
    config_path: PathBuf,
    jobs: Vec<ExportJob>,
}

impl ExportService {
    pub fn new(config_dir: PathBuf) -> Result<Self> {
        fs::create_dir_all(&config_dir)?;
        let config_path = config_dir.join("export-config.json");

        let config = if config_path.exists() {
            let content = fs::read_to_string(&config_path)?;
            serde_json::from_str(&content)?
        } else {
            let default_config = MbExportConfig {
                maya_path: Self::detect_maya(),
                ..Default::default()
            };
            default_config
        };

        Ok(Self {
            config,
            config_path,
            jobs: Vec::new(),
        })
    }

    fn save_config(&self) -> Result<()> {
        let json = serde_json::to_string_pretty(&self.config)?;
        fs::write(&self.config_path, json)?;
        Ok(())
    }

    /// Mayaの自動検出（Windows/macOS/Linux共通パス）
    fn detect_maya() -> Option<String> {
        let candidates = [
            // Windows
            r"C:\Program Files\Autodesk\Maya2024\bin\mayabatch.exe",
            r"C:\Program Files\Autodesk\Maya2023\bin\mayabatch.exe",
            r"C:\Program Files\Autodesk\Maya2025\bin\mayabatch.exe",
            // macOS
            "/Applications/Autodesk/maya2024/Maya.app/Contents/bin/mayabatch",
            "/Applications/Autodesk/maya2023/Maya.app/Contents/bin/mayabatch",
            "/Applications/Autodesk/maya2025/Maya.app/Contents/bin/mayabatch",
            // Linux
            "/usr/autodesk/maya2024/bin/mayabatch",
            "/usr/autodesk/maya2023/bin/mayabatch",
            "/usr/autodesk/maya2025/bin/mayabatch",
        ];

        for path in &candidates {
            if Path::new(path).exists() {
                return Some(path.to_string());
            }
        }
        None
    }

    /// Maya MELスクリプトを生成（MB→FBXエクスポート用）
    fn generate_mel_script(
        &self,
        input_path: &str,
        output_path: &str,
    ) -> String {
        let bake_flag = if self.config.bake_animation {
            "1"
        } else {
            "0"
        };
        let skeleton_flag = if self.config.export_skeleton {
            "1"
        } else {
            "0"
        };

        format!(
            r#"
// Auto-generated by Ars Resource Depot
file -f -o "{input}";
loadPlugin "fbxmaya";
FBXExportBakeComplexAnimation -v {bake};
FBXExportSkeletonDefinitions -v {skeleton};
FBXExportFileVersion -v "{version}";
FBXExport -f "{output}" -s;
quit -f;
"#,
            input = input_path.replace('\\', "/"),
            output = output_path.replace('\\', "/"),
            bake = bake_flag,
            skeleton = skeleton_flag,
            version = self.config.fbx_version,
        )
    }

    /// MBファイルをFBXにエクスポート
    pub fn export_mb_to_fbx(
        &mut self,
        input_path: &str,
        output_dir: Option<&str>,
    ) -> Result<ExportJob> {
        let maya_path = self
            .config
            .maya_path
            .as_ref()
            .ok_or(ExportError::MayaNotFound)?
            .clone();

        if !Path::new(input_path).exists() {
            return Err(ExportError::InputNotFound(input_path.to_string()));
        }

        // 出力パスの決定
        let input = Path::new(input_path);
        let stem = input
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("output");

        let out_dir = output_dir
            .map(PathBuf::from)
            .unwrap_or_else(|| input.parent().unwrap_or(Path::new(".")).to_path_buf());

        let output_path = out_dir.join(format!("{}.fbx", stem));

        let job_id = uuid::Uuid::new_v4().to_string();
        let mut job = ExportJob {
            id: job_id,
            input_path: input_path.to_string(),
            output_path: output_path.to_string_lossy().to_string(),
            config: self.config.clone(),
            status: ExportStatus::Running,
            error: None,
            resource_id: None,
        };

        // MELスクリプトを一時ファイルに書き出し
        let temp_dir = std::env::temp_dir().join("ars-export");
        fs::create_dir_all(&temp_dir)?;
        let mel_path = temp_dir.join(format!("export_{}.mel", &job.id[..8]));
        let mel_script =
            self.generate_mel_script(input_path, &output_path.to_string_lossy());
        fs::write(&mel_path, &mel_script)?;

        // mayabatch実行
        let result = Command::new(&maya_path)
            .arg("-batch")
            .arg("-script")
            .arg(mel_path.to_string_lossy().as_ref())
            .output();

        match result {
            Ok(output) => {
                if output.status.success() {
                    job.status = ExportStatus::Completed;
                } else {
                    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
                    job.status = ExportStatus::Failed;
                    job.error = Some(stderr);
                }
            }
            Err(e) => {
                job.status = ExportStatus::Failed;
                job.error = Some(e.to_string());
            }
        }

        // 一時ファイルを削除
        let _ = fs::remove_file(&mel_path);

        self.jobs.push(job.clone());
        Ok(job)
    }

    /// .mbファイルかどうか判定
    pub fn is_maya_binary(path: &str) -> bool {
        let ext = Path::new(path)
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.to_lowercase());
        matches!(ext.as_deref(), Some("mb") | Some("ma"))
    }

    /// エクスポート設定を更新
    pub fn update_config(&mut self, config: MbExportConfig) -> Result<()> {
        self.config = config;
        self.save_config()?;
        Ok(())
    }

    /// 現在の設定を取得
    pub fn get_config(&self) -> &MbExportConfig {
        &self.config
    }

    /// ジョブ履歴を取得
    pub fn get_jobs(&self) -> &[ExportJob] {
        &self.jobs
    }

    /// ジョブをIDで取得
    pub fn get_job(&self, job_id: &str) -> Option<&ExportJob> {
        self.jobs.iter().find(|j| j.id == job_id)
    }
}
